language: node_js

node_js:
- '8'
- '10'
- '12'

after_success: npm run coveralls

deploy:
  provider: npm
  email: hg8496@cstolz.de
  api_key:
    secure: m1slCS0Lzr7eT0zhX9Fy65vSeGY3uQe4J6sbBI5bssnhju7kobOfGPZ3TTHJFPEGnCE0O5r4NAv6NOnAcQz3iB07YlEfTPAUSThrnXALAYem2aE6zEDgofLtpOSljYr6DgBgsH2DtLSas2ljuB8w4aed3klR2ecAVj4Ok5pwLSALFJ9peRCPuxSClZTGZw/cIuvQybist6FyZrsaGWzbs1+mpiT29lIKQKricu2++Ql0DU9FUxnDfAXg5kBLwpCim3rVbU40nAX10WGePfyA3zCr/o1VvtRhrS/zFm9p8f2rb2RA31RUQDNOSStPLzmpRGbm1bLChoi4d28MEPcTOcFzvavoIStiiIWX5DYCqqjdTepsshG93QDIzeE8x8mCmFejBm1VG+ur1baTy5Ded8BwW9vo4A94GZXioxQKZhkaLTkt3tMCfql90rEyq0n3ief33f9EEfFc+xt+qV7uFsdvl9CTmFYObia842jtuAjHNQyNWiqQsJ874ZJ/eE49oXaYLe9uHJOPNnw2CYsQhJcLf8H3xQAg+VZOy/w49tYoeaeLXkl5tbo9ZYAN7IK77ibhJbqK+ENGovugBcOH0xFbKhHjrfSVxQ1RLYK8++SENfqqcJ1ub25CQzVjYOqfU0quRqROuCRtjZCVGTNWuJSwSX11GUswBb5Tyo9sqHE=
  on:
    tags: true
    repo: hg8496/gridvis-client
    node: 10
  skip_cleanup: true
